<script>
// async函数中存在await  如果程序碰到await  那么陷入阻塞状态
let p1 = new Promise((resolve,reject)=>{
    setTimeout(() => {
        resolve('这是p1  1s');
    }, 1000);
})

let p2 = new Promise((resolve,reject)=>{
    setTimeout(() => {
        resolve('这是p2  3s');
    }, 3000);
})

let p3 = new Promise((resolve,reject)=>{
    setTimeout(() => {
        resolve('这是p3  2s');
    }, 2000);
})

// 这种方式   最先执行的是p2
// p1.then(d=>console.log(d));
// p2.then(d=>console.log(d));
// p3.then(d=>console.log(d));


// 如果说  我们使用async函数
async function test(){
    let v1 = await p1;
    console.log(v1);
    let v2 = await p2;
    console.log(v2);
    let v3 = await p3;
    console.log(v3);
}

test();


</script>